-- =========================================================================
-- Data Tamu Undangan: Agni & Putri (329 Tamu)
-- Tabel: guests
-- Jalankan di Supabase SQL Editor jika ingin menyimpan data ke database.
-- =========================================================================

DO $$
DECLARE
  v_invitation_id UUID := 'e2000000-0000-0000-0000-000000000002';
BEGIN
  INSERT INTO guests (invitation_id, name, guest_code, status)
  VALUES
    (v_invitation_id, 'aan', 'GUEST-001', 'active'),
    (v_invitation_id, 'adel', 'GUEST-002', 'active'),
    (v_invitation_id, 'adenanta', 'GUEST-003', 'active'),
    (v_invitation_id, 'adikagilang', 'GUEST-004', 'active'),
    (v_invitation_id, 'adim bukori', 'GUEST-005', 'active'),
    (v_invitation_id, 'adinugros', 'GUEST-006', 'active'),
    (v_invitation_id, 'adipati argopuro', 'GUEST-007', 'active'),
    (v_invitation_id, 'aditya kukuh', 'GUEST-008', 'active'),
    (v_invitation_id, 'adji', 'GUEST-009', 'active'),
    (v_invitation_id, 'adriansah aliief', 'GUEST-010', 'active'),
    (v_invitation_id, 'afandi fandi', 'GUEST-011', 'active'),
    (v_invitation_id, 'agung', 'GUEST-012', 'active'),
    (v_invitation_id, 'agus cupplis', 'GUEST-013', 'active'),
    (v_invitation_id, 'ahmad', 'GUEST-014', 'active'),
    (v_invitation_id, 'aiziway', 'GUEST-015', 'active'),
    (v_invitation_id, 'ajeng chindy', 'GUEST-016', 'active'),
    (v_invitation_id, 'aji ilham', 'GUEST-017', 'active'),
    (v_invitation_id, 'ajiz mabu', 'GUEST-018', 'active'),
    (v_invitation_id, 'aliapcw', 'GUEST-019', 'active'),
    (v_invitation_id, 'aliev chandra', 'GUEST-020', 'active'),
    (v_invitation_id, 'alif yudhistira', 'GUEST-021', 'active'),
    (v_invitation_id, 'ALIT', 'GUEST-022', 'active'),
    (v_invitation_id, 'alwy', 'GUEST-023', 'active'),
    (v_invitation_id, 'alya', 'GUEST-024', 'active'),
    (v_invitation_id, 'amri', 'GUEST-025', 'active'),
    (v_invitation_id, 'amri fariel', 'GUEST-026', 'active'),
    (v_invitation_id, 'andra cemplon', 'GUEST-027', 'active'),
    (v_invitation_id, 'angga', 'GUEST-028', 'active'),
    (v_invitation_id, 'anggun putri', 'GUEST-029', 'active'),
    (v_invitation_id, 'anricoalamsyah', 'GUEST-030', 'active'),
    (v_invitation_id, 'apped', 'GUEST-031', 'active'),
    (v_invitation_id, 'ari showto', 'GUEST-032', 'active'),
    (v_invitation_id, 'ari simbolon', 'GUEST-033', 'active'),
    (v_invitation_id, 'arif kepek', 'GUEST-034', 'active'),
    (v_invitation_id, 'arinda', 'GUEST-035', 'active'),
    (v_invitation_id, 'arini nur eka', 'GUEST-036', 'active'),
    (v_invitation_id, 'arnold', 'GUEST-037', 'active'),
    (v_invitation_id, 'ary biyangane', 'GUEST-038', 'active'),
    (v_invitation_id, 'astrid', 'GUEST-039', 'active'),
    (v_invitation_id, 'atika gumilar', 'GUEST-040', 'active'),
    (v_invitation_id, 'atmo', 'GUEST-041', 'active'),
    (v_invitation_id, 'azifsu', 'GUEST-042', 'active'),
    (v_invitation_id, 'azza', 'GUEST-043', 'active'),
    (v_invitation_id, 'bagus alezar', 'GUEST-044', 'active'),
    (v_invitation_id, 'bagus fitroh', 'GUEST-045', 'active'),
    (v_invitation_id, 'bandieng', 'GUEST-046', 'active'),
    (v_invitation_id, 'BAYU', 'GUEST-047', 'active'),
    (v_invitation_id, 'BAYU BENJO', 'GUEST-048', 'active'),
    (v_invitation_id, 'bayu eka', 'GUEST-049', 'active'),
    (v_invitation_id, 'bela surya', 'GUEST-050', 'active'),
    (v_invitation_id, 'BELLA', 'GUEST-051', 'active'),
    (v_invitation_id, 'bendot', 'GUEST-052', 'active'),
    (v_invitation_id, 'berley', 'GUEST-053', 'active'),
    (v_invitation_id, 'BIMO TARA', 'GUEST-054', 'active'),
    (v_invitation_id, 'birma', 'GUEST-055', 'active'),
    (v_invitation_id, 'bowo', 'GUEST-056', 'active'),
    (v_invitation_id, 'bramgimb', 'GUEST-057', 'active'),
    (v_invitation_id, 'BRIAN ARINANDA', 'GUEST-058', 'active'),
    (v_invitation_id, 'brillian ahmad', 'GUEST-059', 'active'),
    (v_invitation_id, 'buangheng', 'GUEST-060', 'active'),
    (v_invitation_id, 'chandra kobo', 'GUEST-061', 'active'),
    (v_invitation_id, 'christriya', 'GUEST-062', 'active'),
    (v_invitation_id, 'ciplon', 'GUEST-063', 'active'),
    (v_invitation_id, 'dading', 'GUEST-064', 'active'),
    (v_invitation_id, 'danan bni', 'GUEST-065', 'active'),
    (v_invitation_id, 'danang prayogo', 'GUEST-066', 'active'),
    (v_invitation_id, 'darari', 'GUEST-067', 'active'),
    (v_invitation_id, 'deadty', 'GUEST-068', 'active'),
    (v_invitation_id, 'deddy yanuar', 'GUEST-069', 'active'),
    (v_invitation_id, 'dekjaw', 'GUEST-070', 'active'),
    (v_invitation_id, 'dena angga bali', 'GUEST-071', 'active'),
    (v_invitation_id, 'dendi', 'GUEST-072', 'active'),
    (v_invitation_id, 'denny', 'GUEST-073', 'active'),
    (v_invitation_id, 'denny ok', 'GUEST-074', 'active'),
    (v_invitation_id, 'denny uble', 'GUEST-075', 'active'),
    (v_invitation_id, 'deska', 'GUEST-076', 'active'),
    (v_invitation_id, 'desmaya', 'GUEST-077', 'active'),
    (v_invitation_id, 'dewi dipsy', 'GUEST-078', 'active'),
    (v_invitation_id, 'dhamar', 'GUEST-079', 'active'),
    (v_invitation_id, 'dhiniyah', 'GUEST-080', 'active'),
    (v_invitation_id, 'diangolda', 'GUEST-081', 'active'),
    (v_invitation_id, 'dimas pangestu', 'GUEST-082', 'active'),
    (v_invitation_id, 'dio angga', 'GUEST-083', 'active'),
    (v_invitation_id, 'dista', 'GUEST-084', 'active'),
    (v_invitation_id, 'dulas', 'GUEST-085', 'active'),
    (v_invitation_id, 'dwangga', 'GUEST-086', 'active'),
    (v_invitation_id, 'dwi muhadi', 'GUEST-087', 'active'),
    (v_invitation_id, 'dyah junjing', 'GUEST-088', 'active'),
    (v_invitation_id, 'dyon', 'GUEST-089', 'active'),
    (v_invitation_id, 'edward', 'GUEST-090', 'active'),
    (v_invitation_id, 'eliamarga', 'GUEST-091', 'active'),
    (v_invitation_id, 'ellena', 'GUEST-092', 'active'),
    (v_invitation_id, 'elly dan anchi', 'GUEST-093', 'active'),
    (v_invitation_id, 'ERISYAH', 'GUEST-094', 'active'),
    (v_invitation_id, 'erki', 'GUEST-095', 'active'),
    (v_invitation_id, 'ern.isme', 'GUEST-096', 'active'),
    (v_invitation_id, 'erren', 'GUEST-097', 'active'),
    (v_invitation_id, 'eryn', 'GUEST-098', 'active'),
    (v_invitation_id, 'esa', 'GUEST-099', 'active'),
    (v_invitation_id, 'eva putri', 'GUEST-100', 'active'),
    (v_invitation_id, 'ewsa dovik', 'GUEST-101', 'active'),
    (v_invitation_id, 'fais mur', 'GUEST-102', 'active'),
    (v_invitation_id, 'faisal amblong', 'GUEST-103', 'active'),
    (v_invitation_id, 'fajaradhik', 'GUEST-104', 'active'),
    (v_invitation_id, 'fake paxy', 'GUEST-105', 'active'),
    (v_invitation_id, 'farik', 'GUEST-106', 'active'),
    (v_invitation_id, 'farusi yabid', 'GUEST-107', 'active'),
    (v_invitation_id, 'fatia', 'GUEST-108', 'active'),
    (v_invitation_id, 'fatima kalila', 'GUEST-109', 'active'),
    (v_invitation_id, 'fatrisya', 'GUEST-110', 'active'),
    (v_invitation_id, 'fazyaaf', 'GUEST-111', 'active'),
    (v_invitation_id, 'febi putri', 'GUEST-112', 'active'),
    (v_invitation_id, 'febryan kusuma', 'GUEST-113', 'active'),
    (v_invitation_id, 'feldy', 'GUEST-114', 'active'),
    (v_invitation_id, 'ferly', 'GUEST-115', 'active'),
    (v_invitation_id, 'figa', 'GUEST-116', 'active'),
    (v_invitation_id, 'fuad', 'GUEST-117', 'active'),
    (v_invitation_id, 'galang', 'GUEST-118', 'active'),
    (v_invitation_id, 'galih herlambang', 'GUEST-119', 'active'),
    (v_invitation_id, 'gelegar mentog', 'GUEST-120', 'active'),
    (v_invitation_id, 'geligelo', 'GUEST-121', 'active'),
    (v_invitation_id, 'gesa pamungkas', 'GUEST-122', 'active'),
    (v_invitation_id, 'ghifari', 'GUEST-123', 'active'),
    (v_invitation_id, 'GILANG', 'GUEST-124', 'active'),
    (v_invitation_id, 'gilang risky', 'GUEST-125', 'active'),
    (v_invitation_id, 'GISUL', 'GUEST-126', 'active'),
    (v_invitation_id, 'glangimani', 'GUEST-127', 'active'),
    (v_invitation_id, 'gusti', 'GUEST-128', 'active'),
    (v_invitation_id, 'gusti dan alia', 'GUEST-129', 'active'),
    (v_invitation_id, 'halilintar', 'GUEST-130', 'active'),
    (v_invitation_id, 'hamida', 'GUEST-131', 'active'),
    (v_invitation_id, 'hananta', 'GUEST-132', 'active'),
    (v_invitation_id, 'harlina mega', 'GUEST-133', 'active'),
    (v_invitation_id, 'havandhi', 'GUEST-134', 'active'),
    (v_invitation_id, 'helmi pier', 'GUEST-135', 'active'),
    (v_invitation_id, 'hendrik', 'GUEST-136', 'active'),
    (v_invitation_id, 'heri pong', 'GUEST-137', 'active'),
    (v_invitation_id, 'hestu', 'GUEST-138', 'active'),
    (v_invitation_id, 'hima wiaya brodin', 'GUEST-139', 'active'),
    (v_invitation_id, 'hiras', 'GUEST-140', 'active'),
    (v_invitation_id, 'husen', 'GUEST-141', 'active'),
    (v_invitation_id, 'icha', 'GUEST-142', 'active'),
    (v_invitation_id, 'ichi', 'GUEST-143', 'active'),
    (v_invitation_id, 'ida', 'GUEST-144', 'active'),
    (v_invitation_id, 'igna amy', 'GUEST-145', 'active'),
    (v_invitation_id, 'iis', 'GUEST-146', 'active'),
    (v_invitation_id, 'ikke', 'GUEST-147', 'active'),
    (v_invitation_id, 'imade ade', 'GUEST-148', 'active'),
    (v_invitation_id, 'imona', 'GUEST-149', 'active'),
    (v_invitation_id, 'indah indun', 'GUEST-150', 'active'),
    (v_invitation_id, 'INDUS', 'GUEST-151', 'active'),
    (v_invitation_id, 'inggrid', 'GUEST-152', 'active'),
    (v_invitation_id, 'ipang', 'GUEST-153', 'active'),
    (v_invitation_id, 'iqbal', 'GUEST-154', 'active'),
    (v_invitation_id, 'irfandisk', 'GUEST-155', 'active'),
    (v_invitation_id, 'izha', 'GUEST-156', 'active'),
    (v_invitation_id, 'jarot', 'GUEST-157', 'active'),
    (v_invitation_id, 'jason gregorius', 'GUEST-158', 'active'),
    (v_invitation_id, 'jefrani', 'GUEST-159', 'active'),
    (v_invitation_id, 'johnnyclash', 'GUEST-160', 'active'),
    (v_invitation_id, 'jonathan kev', 'GUEST-161', 'active'),
    (v_invitation_id, 'josh fllush', 'GUEST-162', 'active'),
    (v_invitation_id, 'kamalevi', 'GUEST-163', 'active'),
    (v_invitation_id, 'katon langit', 'GUEST-164', 'active'),
    (v_invitation_id, 'ken', 'GUEST-165', 'active'),
    (v_invitation_id, 'khoirul bali', 'GUEST-166', 'active'),
    (v_invitation_id, 'knsnbll', 'GUEST-167', 'active'),
    (v_invitation_id, 'koh bud', 'GUEST-168', 'active'),
    (v_invitation_id, 'komodoracer', 'GUEST-169', 'active'),
    (v_invitation_id, 'krim', 'GUEST-170', 'active'),
    (v_invitation_id, 'krisna luthfan', 'GUEST-171', 'active'),
    (v_invitation_id, 'kunyup', 'GUEST-172', 'active'),
    (v_invitation_id, 'kurniawan eko', 'GUEST-173', 'active'),
    (v_invitation_id, 'kurniawanap', 'GUEST-174', 'active'),
    (v_invitation_id, 'kusna jamil', 'GUEST-175', 'active'),
    (v_invitation_id, 'lamtoro', 'GUEST-176', 'active'),
    (v_invitation_id, 'lasvellas', 'GUEST-177', 'active'),
    (v_invitation_id, 'levi', 'GUEST-178', 'active'),
    (v_invitation_id, 'lia piuw', 'GUEST-179', 'active'),
    (v_invitation_id, 'lindanoviviya', 'GUEST-180', 'active'),
    (v_invitation_id, 'lintang', 'GUEST-181', 'active'),
    (v_invitation_id, 'llisa tul kantil', 'GUEST-182', 'active'),
    (v_invitation_id, 'lukas', 'GUEST-183', 'active'),
    (v_invitation_id, 'LULU', 'GUEST-184', 'active'),
    (v_invitation_id, 'magda', 'GUEST-185', 'active'),
    (v_invitation_id, 'male', 'GUEST-186', 'active'),
    (v_invitation_id, 'manda', 'GUEST-187', 'active'),
    (v_invitation_id, 'marion', 'GUEST-188', 'active'),
    (v_invitation_id, 'marlin', 'GUEST-189', 'active'),
    (v_invitation_id, 'martin', 'GUEST-190', 'active'),
    (v_invitation_id, 'mas ervan', 'GUEST-191', 'active'),
    (v_invitation_id, 'mas nur', 'GUEST-192', 'active'),
    (v_invitation_id, 'mbah tito', 'GUEST-193', 'active'),
    (v_invitation_id, 'mego', 'GUEST-194', 'active'),
    (v_invitation_id, 'meita', 'GUEST-195', 'active'),
    (v_invitation_id, 'melano', 'GUEST-196', 'active'),
    (v_invitation_id, 'melinda madiun', 'GUEST-197', 'active'),
    (v_invitation_id, 'melly', 'GUEST-198', 'active'),
    (v_invitation_id, 'michel', 'GUEST-199', 'active'),
    (v_invitation_id, 'mirza pradika', 'GUEST-200', 'active'),
    (v_invitation_id, 'muhzaky', 'GUEST-201', 'active'),
    (v_invitation_id, 'nama', 'GUEST-202', 'active'),
    (v_invitation_id, 'nawfal utama', 'GUEST-203', 'active'),
    (v_invitation_id, 'nikenprior', 'GUEST-204', 'active'),
    (v_invitation_id, 'NINGGAR', 'GUEST-205', 'active'),
    (v_invitation_id, 'novia piud', 'GUEST-206', 'active'),
    (v_invitation_id, 'novitawd', 'GUEST-207', 'active'),
    (v_invitation_id, 'nunung', 'GUEST-208', 'active'),
    (v_invitation_id, 'nur hudi', 'GUEST-209', 'active'),
    (v_invitation_id, 'nur tiyasan', 'GUEST-210', 'active'),
    (v_invitation_id, 'octa tata', 'GUEST-211', 'active'),
    (v_invitation_id, 'okky otong', 'GUEST-212', 'active'),
    (v_invitation_id, 'oky dyah', 'GUEST-213', 'active'),
    (v_invitation_id, 'olyn', 'GUEST-214', 'active'),
    (v_invitation_id, 'onesonesan', 'GUEST-215', 'active'),
    (v_invitation_id, 'OZI & RATNA', 'GUEST-216', 'active'),
    (v_invitation_id, 'pahlefi lepek', 'GUEST-217', 'active'),
    (v_invitation_id, 'paijo', 'GUEST-218', 'active'),
    (v_invitation_id, 'paiz kuren', 'GUEST-219', 'active'),
    (v_invitation_id, 'pak fanny sampurna', 'GUEST-220', 'active'),
    (v_invitation_id, 'panadolmerah', 'GUEST-221', 'active'),
    (v_invitation_id, 'panduwicak', 'GUEST-222', 'active'),
    (v_invitation_id, 'pape', 'GUEST-223', 'active'),
    (v_invitation_id, 'petus', 'GUEST-224', 'active'),
    (v_invitation_id, 'pherdy', 'GUEST-225', 'active'),
    (v_invitation_id, 'pipit sarkowi', 'GUEST-226', 'active'),
    (v_invitation_id, 'pitoy', 'GUEST-227', 'active'),
    (v_invitation_id, 'pradana arief', 'GUEST-228', 'active'),
    (v_invitation_id, 'prasmita yoga', 'GUEST-229', 'active'),
    (v_invitation_id, 'pratiti westi', 'GUEST-230', 'active'),
    (v_invitation_id, 'primaaranii', 'GUEST-231', 'active'),
    (v_invitation_id, 'priyo hw', 'GUEST-232', 'active'),
    (v_invitation_id, 'pupun amanda', 'GUEST-233', 'active'),
    (v_invitation_id, 'putra sambiyo (bodong )', 'GUEST-234', 'active'),
    (v_invitation_id, 'qiqi biant', 'GUEST-235', 'active'),
    (v_invitation_id, 'radedya', 'GUEST-236', 'active'),
    (v_invitation_id, 'raga taruna', 'GUEST-237', 'active'),
    (v_invitation_id, 'rahardian seno', 'GUEST-238', 'active'),
    (v_invitation_id, 'rahmat t nugraha', 'GUEST-239', 'active'),
    (v_invitation_id, 'RAMA', 'GUEST-240', 'active'),
    (v_invitation_id, 'rama cuplis', 'GUEST-241', 'active'),
    (v_invitation_id, 'rara', 'GUEST-242', 'active'),
    (v_invitation_id, 'rara patok', 'GUEST-243', 'active'),
    (v_invitation_id, 'ravi wicaksono', 'GUEST-244', 'active'),
    (v_invitation_id, 'ray muntan', 'GUEST-245', 'active'),
    (v_invitation_id, 'rayhan algazali', 'GUEST-246', 'active'),
    (v_invitation_id, 'REA REO', 'GUEST-247', 'active'),
    (v_invitation_id, 'regga pengedar', 'GUEST-248', 'active'),
    (v_invitation_id, 'rehan sepetak', 'GUEST-249', 'active'),
    (v_invitation_id, 'relliart', 'GUEST-250', 'active'),
    (v_invitation_id, 'reza basro', 'GUEST-251', 'active'),
    (v_invitation_id, 'reza JB', 'GUEST-252', 'active'),
    (v_invitation_id, 'reza reso', 'GUEST-253', 'active'),
    (v_invitation_id, 'rezza rez', 'GUEST-254', 'active'),
    (v_invitation_id, 'rifky sigkek', 'GUEST-255', 'active'),
    (v_invitation_id, 'rimang', 'GUEST-256', 'active'),
    (v_invitation_id, 'rindupagi ryan', 'GUEST-257', 'active'),
    (v_invitation_id, 'rio kamil dan istri', 'GUEST-258', 'active'),
    (v_invitation_id, 'riska yudianto sakun', 'GUEST-259', 'active'),
    (v_invitation_id, 'RISTO', 'GUEST-260', 'active'),
    (v_invitation_id, 'riza puri', 'GUEST-261', 'active'),
    (v_invitation_id, 'rizky fatoni', 'GUEST-262', 'active'),
    (v_invitation_id, 'rizkygvndks', 'GUEST-263', 'active'),
    (v_invitation_id, 'rohmawan', 'GUEST-264', 'active'),
    (v_invitation_id, 'romy batawi', 'GUEST-265', 'active'),
    (v_invitation_id, 'rony sajang', 'GUEST-266', 'active'),
    (v_invitation_id, 'ropil', 'GUEST-267', 'active'),
    (v_invitation_id, 'run ngk official', 'GUEST-268', 'active'),
    (v_invitation_id, 'salim', 'GUEST-269', 'active'),
    (v_invitation_id, 'sanda', 'GUEST-270', 'active'),
    (v_invitation_id, 'sarah nila', 'GUEST-271', 'active'),
    (v_invitation_id, 'sartrio gumilang', 'GUEST-272', 'active'),
    (v_invitation_id, 'sekarnndita', 'GUEST-273', 'active'),
    (v_invitation_id, 'septianbayu', 'GUEST-274', 'active'),
    (v_invitation_id, 'seviaca', 'GUEST-275', 'active'),
    (v_invitation_id, 'shendy nasrul', 'GUEST-276', 'active'),
    (v_invitation_id, 'shinta ayu kartika', 'GUEST-277', 'active'),
    (v_invitation_id, 'sindy', 'GUEST-278', 'active'),
    (v_invitation_id, 'siping', 'GUEST-279', 'active'),
    (v_invitation_id, 'sirga', 'GUEST-280', 'active'),
    (v_invitation_id, 'slinkybones owi', 'GUEST-281', 'active'),
    (v_invitation_id, 'sorayaainii', 'GUEST-282', 'active'),
    (v_invitation_id, 'ssstriani', 'GUEST-283', 'active'),
    (v_invitation_id, 'sugeng ivy', 'GUEST-284', 'active'),
    (v_invitation_id, 'sultan ateng', 'GUEST-285', 'active'),
    (v_invitation_id, 'swasti ikak', 'GUEST-286', 'active'),
    (v_invitation_id, 'syahnaz', 'GUEST-287', 'active'),
    (v_invitation_id, 't widi', 'GUEST-288', 'active'),
    (v_invitation_id, 'T Y', 'GUEST-289', 'active'),
    (v_invitation_id, 'taufanlandi', 'GUEST-290', 'active'),
    (v_invitation_id, 'tegar', 'GUEST-291', 'active'),
    (v_invitation_id, 'terry', 'GUEST-292', 'active'),
    (v_invitation_id, 'tista', 'GUEST-293', 'active'),
    (v_invitation_id, 'titis', 'GUEST-294', 'active'),
    (v_invitation_id, 'top zero', 'GUEST-295', 'active'),
    (v_invitation_id, 'totok kopapi', 'GUEST-296', 'active'),
    (v_invitation_id, 'triaditha', 'GUEST-297', 'active'),
    (v_invitation_id, 'tyas kartika', 'GUEST-298', 'active'),
    (v_invitation_id, 'ukiabrori', 'GUEST-299', 'active'),
    (v_invitation_id, 'ully', 'GUEST-300', 'active'),
    (v_invitation_id, 'usrok', 'GUEST-301', 'active'),
    (v_invitation_id, 'uwx', 'GUEST-302', 'active'),
    (v_invitation_id, 'vandripw', 'GUEST-303', 'active'),
    (v_invitation_id, 'vendy yustian', 'GUEST-304', 'active'),
    (v_invitation_id, 'veyradinda', 'GUEST-305', 'active'),
    (v_invitation_id, 'victy', 'GUEST-306', 'active'),
    (v_invitation_id, 'vina', 'GUEST-307', 'active'),
    (v_invitation_id, 'vionacandra', 'GUEST-308', 'active'),
    (v_invitation_id, 'virga', 'GUEST-309', 'active'),
    (v_invitation_id, 'viya', 'GUEST-310', 'active'),
    (v_invitation_id, 'wah22yudi', 'GUEST-311', 'active'),
    (v_invitation_id, 'wahyu cuyek', 'GUEST-312', 'active'),
    (v_invitation_id, 'wahyu mony', 'GUEST-313', 'active'),
    (v_invitation_id, 'wahyu tantra', 'GUEST-314', 'active'),
    (v_invitation_id, 'wakhid', 'GUEST-315', 'active'),
    (v_invitation_id, 'wejang', 'GUEST-316', 'active'),
    (v_invitation_id, 'widha wisnu', 'GUEST-317', 'active'),
    (v_invitation_id, 'widi bagong', 'GUEST-318', 'active'),
    (v_invitation_id, 'winda devi', 'GUEST-319', 'active'),
    (v_invitation_id, 'wisnupratama', 'GUEST-320', 'active'),
    (v_invitation_id, 'yanuar', 'GUEST-321', 'active'),
    (v_invitation_id, 'yanuarf', 'GUEST-322', 'active'),
    (v_invitation_id, 'yasin', 'GUEST-323', 'active'),
    (v_invitation_id, 'yass dinda', 'GUEST-324', 'active'),
    (v_invitation_id, 'yola', 'GUEST-325', 'active'),
    (v_invitation_id, 'yoza', 'GUEST-326', 'active'),
    (v_invitation_id, 'yusuf cahyo', 'GUEST-327', 'active'),
    (v_invitation_id, 'zahra', 'GUEST-328', 'active'),
    (v_invitation_id, 'zhella', 'GUEST-329', 'active');
END $$;